### ISSUE TITLE
Allow also Dexterity Items to be downloaded as pdf

### ISSUE THREAD

**Issue by cekk** [eea/eea.pdf#10]
Hi,
is there a reason why _IPDFAware_ interface is provided only for Dexterity Containers and not for Items?
Here: https://github.com/eea/eea.pdf/blob/master/eea/pdf/subtypes/configure.zcml

What do you think about extend this also with non folderish DX content types?

**Comment by alecghica** [comment]
@cekk sorry for the late reply :) ... nu don't plan to implement that very soon. Feel free to implement it and we'll review&merge your pull request.
