### ISSUE TITLE
Not working on Plone 4

### ISSUE THREAD

**Issue by xnet-services** [eea/eea.pdf#11]
When I try to install it to my Plone4.3.7 (adding the egg and zcml in buildout.cfg) I always get the following error message:
The constraint, 1.1.1, is not consistent with the requirement, 'transaction>=2.0.3'.
While:
  Installing instance.
Error: Bad constraint 1.1.1 transaction>=2.0.3

**Comment by alecghica** [comment]
@xnet-services : it should work with transaction version 1.1.1, there is no constraint/pin on eea.pdf for transaction version 1.1.1 ... looks like is something else (in your setup?) that requires 'transaction>=2.0.3'. We are using it on Plone 4.x with transaction version 1.1.1

**Comment by alecghica** [comment]
@xnet-services I saw you just added https://github.com/eea/eea.converter/issues/3 and I presume you succeeded to install eea.pdf so I will close this issue.
