### ISSUE TITLE
Possible missing zcml entry

### ISSUE THREAD

**Issue by davendal** [eea/eea.pdf#3]
Have had many issues trying to get PDF generation to work in Plone 4.3.4
It finally worked when eea.pdf was added to the eea.pdf buildout under zcml.

David

**Comment by alecghica** [comment]
@davendal thx for pointing this out, we tracked the issue under https://taskman.eionet.europa.eu/issues/23289

**Comment by alecghica** [comment]
Invalid, issue opened for too long.
